-- drop procedures before recreating the query package.
DROP PROCEDURE IF EXISTS sp_query_q15;
DROP PROCEDURE IF EXISTS sp_query_q14;
DROP PROCEDURE IF EXISTS sp_query_q13;
DROP PROCEDURE IF EXISTS sp_query_q12;
DROP PROCEDURE IF EXISTS sp_query_q11;
DROP PROCEDURE IF EXISTS sp_query_q10;
DROP PROCEDURE IF EXISTS sp_query_q9;
DROP PROCEDURE IF EXISTS sp_query_q8;
DROP PROCEDURE IF EXISTS sp_query_q7;
DROP PROCEDURE IF EXISTS sp_query_q6;
DROP PROCEDURE IF EXISTS sp_query_q5;
DROP PROCEDURE IF EXISTS sp_query_q4;
DROP PROCEDURE IF EXISTS sp_query_q3;
DROP PROCEDURE IF EXISTS sp_query_q2;
DROP PROCEDURE IF EXISTS sp_query_q1;
