import type { QueryDefinition } from '@/types';

export const queryCatalog: QueryDefinition[] = [
    {
        id: 'q1',
        number: 1,
        title: 'Top Genres After 2020',
        summary: 'Find genres with the strongest recommendation rates for recently released games.',
        inputs: [
            { name: 'min_release_year', label: 'Earliest Release Year', type: 'number', default: 2021 },
            { name: 'min_reviews', label: 'Minimum Reviews per Genre', type: 'number', default: 10 },
            { name: 'limit', label: 'Rows to Show', type: 'number', default: 15 },
        ],
        chart: { labelColumns: ['GenreName'], valueColumns: ['AvgRecommendationPct'], type: 'bar' },
    },
    {
        id: 'q2',
        number: 2,
        title: 'High-Performing Publishers',
        summary: 'Rank publishers by how many well-reviewed, high-volume games they released.',
        inputs: [
            { name: 'min_reviews', label: 'Minimum Reviews per Game', type: 'number', default: 10000 },
            { name: 'min_recommendation_pct', label: 'Minimum Recommendation %', type: 'number', default: 80 },
            { name: 'limit', label: 'Rows to Show', type: 'number', default: 15 },
        ],
        chart: { labelColumns: ['PublisherName'], valueColumns: ['NumHighPerformingGames'], type: 'bar' },
    },
    {
        id: 'q3',
        number: 3,
        title: 'Best Genre by Release Year',
        summary: 'Show which genre led each release year by average review count per game.',
        inputs: [{ name: 'limit', label: 'Rows to Show', type: 'number', default: 30 }],
        chart: { labelColumns: ['YearReleased', 'GenreName'], valueColumns: ['AvgReviewsPerGame'], type: 'bar' },
    },
    {
        id: 'q4',
        number: 4,
        title: 'Popular but Below Average Sentiment',
        summary: 'Identify games whose review counts beat their year average while recommendation rates lag behind.',
        inputs: [{ name: 'limit', label: 'Rows to Show', type: 'number', default: 20 }],
        chart: { labelColumns: ['Title'], valueColumns: ['ReviewCount', 'RecommendationPct'], type: 'bar' },
    },
    {
        id: 'q5',
        number: 5,
        title: 'Cross-Genre Developer Consistency',
        summary: 'Find developers with high recommendation performance across multiple genres.',
        inputs: [
            { name: 'min_genres', label: 'Minimum Genres', type: 'number', default: 2 },
            { name: 'min_games', label: 'Minimum Games', type: 'number', default: 2 },
            { name: 'min_reviews', label: 'Minimum Reviews', type: 'number', default: 20 },
            { name: 'limit', label: 'Rows to Show', type: 'number', default: 20 },
        ],
        chart: { labelColumns: ['DeveloperName'], valueColumns: ['AvgRecommendationPct'], type: 'bar' },
    },
    {
        id: 'q6',
        number: 6,
        title: 'Price vs Popularity by Genre',
        summary: 'Compare review activity and recommendation rates across price bands within each genre.',
        inputs: [{ name: 'limit', label: 'Rows to Show', type: 'number', default: 30 }],
        chart: { labelColumns: ['GenreName', 'PriceRange'], valueColumns: ['AvgReviewsPerGame'], type: 'bar' },
    },
    {
        id: 'q7',
        number: 7,
        title: 'Genre Growth Over Time',
        summary: 'Track genre growth in both released games and review activity over time.',
        inputs: [
            { name: 'genre_keyword', label: 'Optional Genre Keyword', type: 'text', default: '' },
            { name: 'limit', label: 'Rows to Show', type: 'number', default: 40 },
        ],
        chart: { labelColumns: ['ReleaseYear', 'GenreName'], valueColumns: ['TotalReviews'], type: 'bar' },
    },
    {
        id: 'q8',
        number: 8,
        title: 'Multiplayer Engagement Tags',
        summary: 'Measure which tags correlate with stronger engagement among multiplayer-supported games.',
        inputs: [
            { name: 'min_reviews', label: 'Minimum Reviews per Tag', type: 'number', default: 10 },
            { name: 'feature_keyword', label: 'Feature Keyword', type: 'text', default: 'multi' },
            { name: 'limit', label: 'Rows to Show', type: 'number', default: 20 },
        ],
        chart: { labelColumns: ['TagName'], valueColumns: ['AvgHelpfulVotes', 'AvgHoursPlayed'], type: 'bar' },
    },
    {
        id: 'q9',
        number: 9,
        title: 'Popularity vs Sentiment Mismatch',
        summary: 'Rank games whose review volume and recommendation sentiment diverge the most.',
        inputs: [
            { name: 'min_reviews', label: 'Minimum Reviews per Game', type: 'number', default: 20 },
            { name: 'limit', label: 'Rows to Show', type: 'number', default: 20 },
        ],
        chart: { labelColumns: ['Title'], valueColumns: ['MismatchScore'], type: 'bar' },
    },
    {
        id: 'q10',
        number: 10,
        title: 'Popular Publishers',
        summary: 'Rank publishers by how many popular games they released and their review performance.',
        inputs: [
            { name: 'min_reviews', label: 'Minimum Reviews per Game', type: 'number', default: 20 },
            { name: 'limit', label: 'Rows to Show', type: 'number', default: 20 },
        ],
        chart: { labelColumns: ['PublisherName'], valueColumns: ['NumPopularGames'], type: 'bar' },
    },
    {
        id: 'q11',
        number: 11,
        title: 'Multi-Platform Review Activity',
        summary: 'Show how review activity changes for games that support two or more operating systems.',
        inputs: [
            { name: 'min_platforms', label: 'Minimum Supported Platforms', type: 'number', default: 2 },
            { name: 'limit', label: 'Rows to Show', type: 'number', default: 20 },
        ],
        chart: { labelColumns: ['Title'], valueColumns: ['ReviewCount', 'RecommendationPct'], type: 'bar' },
    },
    {
        id: 'q12',
        number: 12,
        title: 'Traits of Top-Reviewed Games',
        summary: 'Profile the genre and price range patterns of the most reviewed games.',
        inputs: [
            { name: 'top_limit', label: 'How Many Top-Reviewed Games', type: 'number', default: 50 },
            { name: 'limit', label: 'Rows to Show', type: 'number', default: 25 },
        ],
        chart: { labelColumns: ['GenreName', 'PriceRange'], valueColumns: ['NumTopGames'], type: 'bar' },
    },
    {
        id: 'q13',
        number: 13,
        title: 'Best Release Months',
        summary: 'Compare release months by average reviews per game and recommendation rate.',
        inputs: [{ name: 'limit', label: 'Rows to Show', type: 'number', default: 12 }],
        chart: { labelColumns: ['ReleaseMonth'], valueColumns: ['AvgReviewsPerGame', 'AvgRecommendationPct'], type: 'bar' },
    },
    {
        id: 'q14',
        number: 14,
        title: 'Largest Review-Count Gaps',
        summary: 'Compare same-year, same-genre games with the biggest review-count gaps.',
        inputs: [{ name: 'limit', label: 'Rows to Show', type: 'number', default: 50 }],
        chart: { labelColumns: ['ReleaseYear', 'GenreName'], valueColumns: ['ReviewCountGap'], type: 'bar' },
    },
    {
        id: 'q15',
        number: 15,
        title: 'Developer Improvement Over Time',
        summary: 'Measure how recommendation rate and review count change from a developer’s early to late releases.',
        inputs: [{ name: 'limit', label: 'Rows to Show', type: 'number', default: 20 }],
        chart: { labelColumns: ['DeveloperName'], valueColumns: ['RecommendationImprovement', 'ReviewCountImprovement'], type: 'bar' },
    },
];
