LOAD DATA LOCAL INFILE 'clean/Publisher.csv'
INTO TABLE Publisher
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES
(PublisherName);

LOAD DATA LOCAL INFILE 'clean/Developer.csv'
INTO TABLE Developer
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES
(DeveloperName, @DeveloperType)
SET DeveloperType = NULLIF(@DeveloperType, '');

LOAD DATA LOCAL INFILE 'clean/Platform.csv'
INTO TABLE Platform
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES
(PlatformName);

LOAD DATA LOCAL INFILE 'clean/Genre.csv'
INTO TABLE Genre
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES
(GenreName);

LOAD DATA LOCAL INFILE 'clean/Tag.csv'
INTO TABLE Tag
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES
(TagName);

LOAD DATA LOCAL INFILE 'clean/Feature.csv'
INTO TABLE Feature
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES
(FeatureName);

LOAD DATA LOCAL INFILE 'clean/Game.csv'
INTO TABLE Game
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES
(GameID, Title, @ReleaseDate, Price)
SET ReleaseDate = STR_TO_DATE(@ReleaseDate, '%Y-%m-%d');

LOAD DATA LOCAL INFILE 'clean/Review.csv'
INTO TABLE Review
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES
(ReviewID, @ReviewDate, IsRecommended, HelpfulVotes, @HoursPlayed, GameID)
SET ReviewDate = STR_TO_DATE(@ReviewDate, '%Y-%m-%d'),
    HoursPlayed = NULLIF(@HoursPlayed, '');

LOAD DATA LOCAL INFILE 'clean/DevelopedBy.csv'
INTO TABLE DevelopedBy
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES
(GameID, DeveloperName);

LOAD DATA LOCAL INFILE 'clean/Supports.csv'
INTO TABLE Supports
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES
(GameID, PlatformName);

LOAD DATA LOCAL INFILE 'clean/PublishedBy.csv'
INTO TABLE PublishedBy
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES
(GameID, PublisherName);

LOAD DATA LOCAL INFILE 'clean/ClassifiedAs.csv'
INTO TABLE ClassifiedAs
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES
(GameID, GenreName);

LOAD DATA LOCAL INFILE 'clean/TaggedWith.csv'
INTO TABLE TaggedWith
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES
(GameID, TagName);

LOAD DATA LOCAL INFILE 'clean/HasFeatures.csv'
INTO TABLE HasFeatures
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES
(GameID, FeatureName);